name: Build skandha unstable docker image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - "ix-develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Get package version
        id: get_version
        run: echo version=$(git rev-parse --short "$GITHUB_SHA") >> $GITHUB_OUTPUT
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/illuminexswap/skandha
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=unstable
            type=raw,value=${{ steps.get_version.outputs.version }},prefix=unstable-
          flavor:
            latest=false
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
